### PR TITLE
Fix/build errors

### PR DESCRIPTION
**Pull request by christinaroise**
This fixes a lot of type and build errors spread across the repo. It'd be nice to get this merged before any other changes.

### CODE REVIEW

**Comment by mathiazom** [comment]
Do we want to merge with `main` and not `feature/new-variant`?

**Review by anemne — COMMENTED** [review]
Look good to me, but do you want to merge these changes to main already?

**Comment by christinaroise** [comment]
Good catch! Im still finding vercel errors and forgot to convert this back to draft!

**Comment by mathiazom** [comment]
It should be `feat/new-variant`, not `feat/new-website`, right? Not sure what the latter branch is for 🤔

**Pull request merged**
